export const GET_ARRAY_POKEMONS_TYPES = 'GET_ARRAY_POKEMONS_TYPES';
export const ADD_TYPE_TO_LIST = 'ADD_TYPE_TO_LIST';
export const REMOVE_TYPE_FROM_LIST = 'REMOVE_TYPE_FROM_LIST';
export const FILTER_POKEMONS = 'FILTER_POKEMONS';
export const FIND_POKEMONS = 'FIND_POKEMONS';
